---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/querti/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-test-mintmaker
