apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - application-api
  - has
  - release
  - integration
  - enterprise-contract
  - build-service
  - pipeline-service
  - build-templates
  - etcd-defrag
  - internal-services
  - image-controller
  - project-controller
  - spacerequest-cleaner
  - mintmaker
  - nvme-storage-configurator
  - tempo
  - notification-controller
  - workspaces
  - proactive-scaler
  - konflux-ui
  - konflux-rbac
  - konflux-info
  - namespace-lister
components:
  - ../../../k-components/inject-infra-deployments-repo-details
